### ISSUE TITLE
Undefined Property: $Get....

### ISSUE THREAD

**Issue by daestru** [daestru/DevDynasty#3]
Uncovered during call at 11/29 at 6:05:

Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3 in C:\xampp\htdocs\CS445Portfolio\src\DB\managePortfolioDB.php:29 Stack trace: #0 C:\xampp\htdocs\CS445Portfolio\src\DB\managePortfolioDB.php(29): mysqli->query('UPDATE `portfol...') #1 {main} thrown in C:\xampp\htdocs\CS445Portfolio\src\DB\managePortfolioDB.php on line 29

**Comment by Eloc345** [comment]
There was an error in the syntax of the code. This was remedied by analyzing curly brackets and adding them where needed.
